import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const newChurches = [
  // MICHIGAN - from postmillennial/abolitionist network
  {
    name: "Colwood Church",
    denomination: "Non-Denominational",
    address: "1840 N Colling Rd",
    city: "Caro",
    state: "MI",
    zip: "48723",
    latitude: 43.5093,
    longitude: -83.4018,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Postmillennial. Pastor Jason Garwood. Listed on postmillennial church directory.",
    description: "A postmillennial church in Caro, MI.",
    approved: true,
  },
  {
    name: "Providence Church",
    denomination: "Non-Denominational",
    address: "Caro",
    city: "Caro",
    state: "MI",
    zip: "48723",
    latitude: 43.4909,
    longitude: -83.3968,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor Jacob Hanby. Listed on postmillennial church directory.",
    description: "A church in Caro, MI connected to the postmillennial network.",
    approved: true,
  },
  {
    name: "Faith Victory Fellowship",
    denomination: "Non-Denominational",
    address: "Buchanan",
    city: "Buchanan",
    state: "MI",
    zip: "49107",
    latitude: 41.8275,
    longitude: -86.3611,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor David Mitchell. Listed on postmillennial church directory.",
    description: "A postmillennial fellowship in Buchanan, MI.",
    approved: true,
  },
  {
    name: "OneLife Church",
    denomination: "Non-Denominational",
    address: "Grand Blanc",
    city: "Grand Blanc",
    state: "MI",
    zip: "48439",
    latitude: 42.9275,
    longitude: -83.6299,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor Eric Stewart. Listed on postmillennial church directory.",
    description: "A postmillennial church in Grand Blanc, MI.",
    approved: true,
  },
  {
    name: "New Life Fellowship",
    denomination: "Non-Denominational",
    address: "Holland",
    city: "Holland",
    state: "MI",
    zip: "49423",
    latitude: 42.7876,
    longitude: -86.1089,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor Mart Novak. Listed on postmillennial church directory.",
    description: "A postmillennial fellowship in Holland, MI.",
    approved: true,
  },
  {
    name: "CityGate Church",
    denomination: "Non-Denominational",
    address: "Portage",
    city: "Portage",
    state: "MI",
    zip: "49002",
    latitude: 42.2012,
    longitude: -85.5800,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor John Gilfillan. Listed on postmillennial church directory.",
    description: "A postmillennial church in Portage, MI.",
    approved: true,
  },
  // KEY NATIONAL - abolitionist conference speakers/connected churches
  {
    name: "Sovereign King Church",
    denomination: "Reformed",
    address: "Jeffersonville",
    city: "Jeffersonville",
    state: "IN",
    zip: "47130",
    latitude: 38.2776,
    longitude: -85.7372,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor Joseph Spurgeon. Postmillennial, Reformed. Connected to abolitionist movement — refused to sign the Antioch Declaration. Member of Evangel Presbytery.",
    description: "A Reformed church in Jeffersonville, IN led by Pastor Joseph Spurgeon.",
    approved: true,
  },
  {
    name: "Faith Bible Church",
    denomination: "Independent",
    address: "4907 E Highway 34",
    city: "Sharpsburg",
    state: "GA",
    zip: "30277",
    latitude: 33.3365,
    longitude: -84.6455,
    website: "https://faithbiblechurch.us",
    phone: "(770) 252-8244",
    zionistStance: "unknown",
    theologicalNotes: "Pastor John Crotts. Home of 'Rescue the Preborn' ministry — active abortion clinic outreach, biblical counseling, jail ministry. Connected to abolitionist movement.",
    description: "An independent Bible church in Sharpsburg, GA known for its Rescue the Preborn ministry.",
    approved: true,
  },
  {
    name: "Reformation Hope Church",
    denomination: "Non-Denominational",
    address: "Brookfield",
    city: "Brookfield",
    state: "WI",
    zip: "53005",
    latitude: 43.0606,
    longitude: -88.1065,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor Wayne C. Sedlak. Listed on postmillennial church directory. Also has Jackson, WI location.",
    description: "A postmillennial church in the Milwaukee area.",
    approved: true,
  },
  {
    name: "Jubilee Christian Family Church",
    denomination: "Non-Denominational",
    address: "Franklin",
    city: "Franklin",
    state: "WI",
    zip: "53132",
    latitude: 42.8886,
    longitude: -88.0384,
    website: null,
    phone: null,
    zionistStance: "unknown",
    theologicalNotes: "Pastor Wayne Rohde. Listed on postmillennial church directory. Milwaukee area, near Mercy Seat Christian Church.",
    description: "A postmillennial church in Franklin, WI.",
    approved: true,
  },
]

async function main() {
  for (const church of newChurches) {
    const existing = await prisma.church.findFirst({
      where: { name: church.name, state: church.state },
    })
    if (existing) {
      console.log(`Skipping "${church.name}" (${church.state}) — already exists (id: ${existing.id})`)
      continue
    }
    const created = await prisma.church.create({ data: church })
    console.log(`Added "${created.name}" in ${created.city}, ${created.state} (id: ${created.id})`)
  }
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
