import * as fs from 'fs'
const all = JSON.parse(fs.readFileSync('data/research-queue/rpcna_extracted.json', 'utf-8'))
const vacant = all.filter((r: any) => r.pastor && /vacant/i.test(r.pastor))
console.log('Vacant pastors:', vacant.length)
vacant.forEach((r: any) => console.log('  ' + r.churchId + ' ' + r.pageTitle))
console.log('\nNo address:')
all.filter((r: any) => !r.address?.street).forEach((r: any) => console.log('  ' + r.churchId + ' ' + r.pageTitle))
console.log('\nNo phone:')
all.filter((r: any) => !r.phone).forEach((r: any) => console.log('  ' + r.churchId + ' ' + r.pageTitle))
console.log('\nNo website:')
all.filter((r: any) => !r.website).forEach((r: any) => console.log('  ' + r.churchId + ' ' + r.pageTitle))
console.log('\nLeadership role inventory:')
const roles = new Map<string, number>()
for (const r of all) for (const l of r.leadership || []) roles.set(l.role, (roles.get(l.role) || 0) + 1)
;[...roles.entries()].sort((a, b) => b[1] - a[1]).forEach(([r, n]) => console.log('  ' + n + '  ' + r))
