import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const churches = [
  {
    name: "Grace Community Church",
    denomination: "Non-Denominational",
    address: "13248 Roscoe Blvd",
    city: "Sun Valley",
    state: "CA",
    zip: "91352",
    latitude: 34.2547,
    longitude: -118.3962,
    zionistStance: "yes",
    theologicalNotes: "Dispensational premillennialism. Strong Israel-support teaching.",
    description: "A large evangelical church known for biblical exposition and commitment to sound doctrine.",
    approved: true,
  },
  {
    name: "Founders Baptist Church",
    denomination: "Southern Baptist",
    address: "24724 Aldine Westfield Rd",
    city: "Spring",
    state: "TX",
    zip: "77373",
    latitude: 30.0799,
    longitude: -95.3863,
    zionistStance: "no",
    theologicalNotes: "Reformed Baptist, 1689 Confession. Covenantal theology, postmillennial leanings.",
    description: "A Reformed Baptist church focused on the doctrines of grace and expository preaching.",
    approved: true,
  },
  {
    name: "Apologia Church",
    denomination: "Reformed Baptist",
    address: "2024 S Arizona Ave",
    city: "Mesa",
    state: "AZ",
    zip: "85210",
    latitude: 33.3942,
    longitude: -111.8413,
    zionistStance: "no",
    theologicalNotes: "Postmillennial, theonomic. Rejects dispensationalism and Christian Zionism.",
    description: "Known for apologetics ministry, committed to Reformed theology and cultural engagement.",
    approved: true,
  },
  {
    name: "Covenant Baptist Church",
    denomination: "Reformed Baptist",
    address: "5440 SW 37th St",
    city: "Topeka",
    state: "KS",
    zip: "66614",
    latitude: 38.9817,
    longitude: -95.7376,
    zionistStance: "no",
    theologicalNotes: "1689 Federalism. Covenantal, amillennial. No distinction between Israel and the Church.",
    description: "A confessional Reformed Baptist church committed to the 1689 London Baptist Confession of Faith.",
    approved: true,
  },
  {
    name: "Christ Fellowship Baptist Church",
    denomination: "Southern Baptist",
    address: "5100 S US Highway 17/92",
    city: "Casselberry",
    state: "FL",
    zip: "32707",
    latitude: 28.6614,
    longitude: -81.3275,
    zionistStance: "yes",
    theologicalNotes: "Dispensational. Teaches a distinct future for national Israel.",
    description: "A gospel-centered church focused on biblical preaching and community outreach in central Florida.",
    approved: true,
  },
  {
    name: "Cornerstone Church",
    denomination: "Non-Denominational",
    address: "18755 Stone Oak Pkwy",
    city: "San Antonio",
    state: "TX",
    zip: "78258",
    latitude: 29.6120,
    longitude: -98.4861,
    zionistStance: "yes",
    theologicalNotes: "Strongly dispensational. Hosts annual pro-Israel events. CUFI affiliated.",
    description: "A large evangelical church with a strong emphasis on biblical teaching and support for Israel.",
    approved: true,
  },
  {
    name: "McLean Bible Church",
    denomination: "Non-Denominational",
    address: "8925 Leesburg Pike",
    city: "Vienna",
    state: "VA",
    zip: "22182",
    latitude: 38.9121,
    longitude: -77.2270,
    zionistStance: "unknown",
    theologicalNotes: "Evangelical megachurch. Zionist stance not prominently stated.",
    description: "An evangelical megachurch in the Washington D.C. area focused on biblical teaching and community impact.",
    approved: true,
  },
  {
    name: "Heritage Baptist Church",
    denomination: "Independent Baptist",
    address: "14510 Sperry Rd",
    city: "Newbury",
    state: "OH",
    zip: "44065",
    latitude: 41.4633,
    longitude: -81.2191,
    zionistStance: "yes",
    theologicalNotes: "Traditional dispensational. KJV-preferred.",
    description: "A traditional Baptist church holding to conservative, biblical values in northeast Ohio.",
    approved: true,
  },
  {
    name: "Trinity Bible Church",
    denomination: "Non-Denominational",
    address: "2002 E 8th St",
    city: "Dallas",
    state: "TX",
    zip: "75203",
    latitude: 32.7724,
    longitude: -96.7770,
    zionistStance: "no",
    theologicalNotes: "Covenantal Reformed. Amillennial eschatology. Church = true Israel.",
    description: "A church committed to verse-by-verse Bible teaching and Reformed theology in Dallas.",
    approved: true,
  },
  {
    name: "Capitol Hill Baptist Church",
    denomination: "Southern Baptist",
    address: "525 A St NE",
    city: "Washington",
    state: "DC",
    zip: "20002",
    latitude: 38.8893,
    longitude: -77.0020,
    zionistStance: "unknown",
    theologicalNotes: "9Marks affiliated. Focus on ecclesiology over eschatology. Zionist stance not emphasized.",
    description: "Known for commitment to expository preaching, meaningful church membership, and biblical church leadership.",
    approved: true,
  },
  {
    name: "First Baptist Dallas",
    denomination: "Southern Baptist",
    address: "1707 San Jacinto St",
    city: "Dallas",
    state: "TX",
    zip: "75201",
    latitude: 32.7837,
    longitude: -96.7981,
    zionistStance: "yes",
    theologicalNotes: "Dispensational premillennial. Vocal support for Israel from leadership.",
    description: "A historic Southern Baptist church in downtown Dallas with a commitment to biblical authority.",
    approved: true,
  },
  {
    name: "Community Bible Church",
    denomination: "Non-Denominational",
    address: "2477 N Loop 1604 W",
    city: "San Antonio",
    state: "TX",
    zip: "78248",
    latitude: 29.5850,
    longitude: -98.5290,
    zionistStance: "yes",
    theologicalNotes: "Dispensational. Teaches pre-tribulation rapture and Israel's prophetic role.",
    description: "A Bible-teaching church focused on making disciples and serving the San Antonio community.",
    approved: true,
  },
  {
    name: "Providence Church",
    denomination: "Presbyterian (PCA)",
    address: "6014 Oleander Dr",
    city: "Wilmington",
    state: "NC",
    zip: "28403",
    latitude: 34.1985,
    longitude: -77.8865,
    zionistStance: "no",
    theologicalNotes: "Confessional Presbyterian. Westminster Standards. Covenantal amillennialism.",
    description: "A Presbyterian church in the PCA tradition with a focus on Reformed worship and teaching.",
    approved: true,
  },
  {
    name: "Redeemer Church",
    denomination: "Southern Baptist",
    address: "3075 Old Alabama Rd",
    city: "Alpharetta",
    state: "GA",
    zip: "30022",
    latitude: 34.0467,
    longitude: -84.2383,
    zionistStance: "unknown",
    theologicalNotes: "Reformed soteriology. Eschatological stance not prominently taught.",
    description: "A gospel-centered church committed to Reformed theology and community engagement in metro Atlanta.",
    approved: true,
  },
  {
    name: "Bethlehem Baptist Church",
    denomination: "Baptist General Conference",
    address: "720 13th Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55415",
    latitude: 44.9669,
    longitude: -93.2589,
    zionistStance: "no",
    theologicalNotes: "Historic premillennial but not dispensational. Does not hold to Christian Zionism.",
    description: "A historic church known for its commitment to joyful theology and global missions.",
    approved: true,
  },
  // ── New non-Zionist churches ──
  {
    name: "Refuge Church",
    denomination: "Reformed",
    address: "607 26th Street",
    city: "Ogden",
    state: "UT",
    zip: "84401",
    latitude: 41.2184,
    longitude: -111.9647,
    website: "https://www.refugeutah.org/",
    zionistStance: "no",
    theologicalNotes: "Confessionally Reformed — elders subscribe to Westminster Confession or 1689 LBCF. Postmillennial leanings. Covenant theology rejects dispensationalism. Pastors Brian Sauve and Eric Conn are vocal critics of Christian Zionism on X.",
    description: "Reformed church in Ogden led by a plurality of pastor/elders. Self-described 'jovial Calvinists' practicing baptismal catholicity.",
    approved: true,
  },
  {
    name: "Covenant Bible Church",
    denomination: "Reformed Baptist",
    address: "13470 E State Highway 29, Suite 100",
    city: "Georgetown",
    state: "TX",
    zip: "78626",
    latitude: 30.6351,
    longitude: -97.4765,
    website: "https://covenantbible.org/",
    phone: "(469) 487-6298",
    zionistStance: "no",
    theologicalNotes: "1689 LBCF. Postmillennial, general equity theonomy. Pastor Joel Webbon (Right Response Ministries) is vocally anti-dispensationalist and non-Zionist. Christian Reconstructionist influence.",
    description: "A Bible-believing, Bible-preaching church in the Austin metro area. Affiliated with Right Response Ministries.",
    approved: true,
  },
  {
    name: "Christ Church",
    denomination: "CREC",
    address: "820 Dominion Way",
    city: "Moscow",
    state: "ID",
    zip: "83843",
    latitude: 46.7317,
    longitude: -117.0028,
    website: "https://christkirk.com/",
    phone: "(208) 882-2034",
    zionistStance: "no",
    theologicalNotes: "Postmillennial, covenant theology, Calvinist. Doug Wilson is one of the most prominent voices against dispensationalism in American Christianity. Explicitly rejects Christian Zionism as theological error.",
    description: "Flagship church of the CREC denomination and center of the Moscow, Idaho Reformed community. ~3,000 members. Associated with New Saint Andrews College and Canon Press.",
    approved: true,
  },
  {
    name: "Dominion Covenant Church",
    denomination: "CPC (Presbyterian)",
    address: "6104 Irvington Road",
    city: "Omaha",
    state: "NE",
    zip: "68134",
    latitude: 41.3143,
    longitude: -96.0527,
    website: "https://dominioncovenantchurch.com/",
    phone: "(402) 819-9953",
    zionistStance: "no",
    theologicalNotes: "Theonomic, postmillennial, Reformed. Dr. Phillip Kayser is a prominent theonomist. Covenant theology is foundational — inherently non-Zionist/anti-dispensationalist.",
    description: "Mission: 'Promoting and enjoying the dominion of King Jesus over every area of life.' Founded by Dr. Phillip Kayser.",
    approved: true,
  },
  {
    name: "King's Way Reformed Church",
    denomination: "Reformed",
    address: "1100 E Sheldon St",
    city: "Prescott",
    state: "AZ",
    zip: "86301",
    latitude: 34.5452,
    longitude: -112.4559,
    website: "https://kingswaybible.org/",
    zionistStance: "no",
    theologicalNotes: "Postmillennial, general equity theonomy. Westminster Confession. Pastor Dale Partridge (Reformation Seminary) is outspokenly anti-dispensationalist and non-Zionist.",
    description: "A Reformed church plant in Prescott raising up Gospel-fluent families. Dale Partridge also founded Reformation Seminary.",
    approved: true,
  },
  {
    name: "Trinity Church",
    denomination: "CREC",
    address: "720 E Poplar Ave",
    city: "Coeur d'Alene",
    state: "ID",
    zip: "83814",
    latitude: 47.6921,
    longitude: -116.7759,
    website: "https://trinitycda.org/",
    phone: "(208) 615-5075",
    zionistStance: "no",
    theologicalNotes: "CREC church — covenant theology, Reformed soteriology. Rejects dispensationalism. Part of the broader Idaho Reformed community.",
    description: "CREC church in northern Idaho, part of the broader Moscow/Idaho Reformed community. Worshiping together since 2006.",
    approved: true,
  },
  {
    name: "Christ Church Spokane",
    denomination: "CREC",
    address: "228 E Gordon Ave",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    latitude: 47.6907,
    longitude: -117.4070,
    website: "https://ccspokane.com/",
    phone: "(509) 329-0314",
    zionistStance: "no",
    theologicalNotes: "CREC member — covenant theology, Reformed. Rejects dispensationalism. Non-Zionist by covenantal conviction.",
    description: "CREC church in Spokane serving the inland Northwest Reformed community.",
    approved: true,
  },
  {
    name: "Reformation Covenant Church",
    denomination: "CREC",
    address: "1201 JQ Adams St",
    city: "Oregon City",
    state: "OR",
    zip: "97045",
    latitude: 45.3579,
    longitude: -122.5972,
    website: "https://reformationcovenant.org/",
    phone: "(503) 656-9444",
    zionistStance: "no",
    theologicalNotes: "CREC member — covenant theology, Reformed. Rejects dispensationalism. Established 1983, deep roots in Reformation theology.",
    description: "One of the older CREC congregations, worshiping, learning, and doing life together since 1983.",
    approved: true,
  },
  {
    name: "The Shepherd's Church",
    denomination: "CREC",
    address: "10 Jean Ave, Suite 12",
    city: "Chelmsford",
    state: "MA",
    zip: "01824",
    latitude: 42.6222,
    longitude: -71.3597,
    website: "https://www.theshepherds.church/",
    phone: "(978) 304-6265",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, confessional, family-integrated. Covenant theology rejects dispensationalism.",
    description: "Founded in 2019. A reformed, confessional, family-integrated church serving the Chelmsford/Lowell area of Massachusetts.",
    approved: true,
  },
  {
    name: "Providence Church Pensacola",
    denomination: "CREC",
    address: "9600 N Palafox St",
    city: "Pensacola",
    state: "FL",
    zip: "32534",
    latitude: 30.5362,
    longitude: -87.2752,
    website: "https://www.providencepensacola.org/",
    phone: "(850) 377-3049",
    zionistStance: "no",
    theologicalNotes: "CREC member. Westminster Confession of Faith (1646) and Heidelberg Catechism. Robustly Calvinistic and covenantal. Rejects dispensationalism.",
    description: "CREC church led by Rev. Dr. Uriesou Brito. Moved to new property in January 2026 after 17+ years at Trinitas Christian School.",
    approved: true,
  },
  {
    name: "Holy Trinity Reformed Church",
    denomination: "CREC",
    address: "3747 Trinity Church Road",
    city: "Concord",
    state: "NC",
    zip: "28027",
    latitude: 35.4655,
    longitude: -80.6881,
    website: "http://www.htrchurch.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Rejects dispensationalism. Non-Zionist by covenantal conviction.",
    description: "CREC church in the Charlotte metro area of North Carolina.",
    approved: true,
  },
  {
    name: "Christ the King Church",
    denomination: "CREC",
    address: "1223 Grove Road",
    city: "Greenville",
    state: "SC",
    zip: "29605",
    latitude: 34.8071,
    longitude: -82.4218,
    website: "http://www.christkingchurch.com/",
    phone: "(864) 202-6920",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Affirms ecumenical creeds. Rejects dispensationalism.",
    description: "CREC church in Greenville, SC. Affirms the ecumenical creeds and Reformed theology.",
    approved: true,
  },
  {
    name: "Providence Church Lynchburg",
    denomination: "CREC",
    address: "108 Melinda Dr",
    city: "Lynchburg",
    state: "VA",
    zip: "24502",
    latitude: 37.3450,
    longitude: -79.1935,
    website: "https://www.providencekirk.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Rejects dispensationalism. Founded as home Bible study in 2000.",
    description: "CREC church in Lynchburg, Virginia. Founded by Pastor Virgil Hurt in December 2000.",
    approved: true,
  },
  {
    name: "Trinity Church Kirkland",
    denomination: "CREC",
    address: "6400 108th Ave NE",
    city: "Kirkland",
    state: "WA",
    zip: "98033",
    latitude: 47.6639,
    longitude: -122.1961,
    website: "https://trinitykirk.org/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Rejects dispensationalism. Serves the Seattle metro eastside.",
    description: "CREC church in the Seattle metro area serving the eastside communities.",
    approved: true,
  },
  {
    name: "Tri-City Covenant Church",
    denomination: "CREC",
    address: "150 West High Street",
    city: "Somersworth",
    state: "NH",
    zip: "03878",
    latitude: 43.2605,
    longitude: -70.8885,
    website: "https://tricitycovenant.com/",
    phone: "(603) 692-2093",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformational Catholic identity. Covenant theology rejects dispensationalism.",
    description: "A Reformational Catholic church serving Somersworth, Rochester, and Dover, New Hampshire. Joined CREC in 2008.",
    approved: true,
  },
  {
    name: "Phoenix Reformed Baptist Church",
    denomination: "Reformed Baptist",
    address: "3805 N 12th St",
    city: "Phoenix",
    state: "AZ",
    zip: "85014",
    latitude: 33.4912,
    longitude: -112.0563,
    website: "https://prbc.org/",
    phone: "(602) 264-7223",
    zionistStance: "no",
    theologicalNotes: "Reformed Baptist, 1689 framework. Postmillennial leanings. Covenant theology rejects dispensationalism.",
    description: "A Reformed Baptist fellowship emphasizing worship through prayer and consistent, in-depth proclamation of Scripture.",
    approved: true,
  },
  {
    name: "Grace Life Church of Dallas",
    denomination: "Reformed",
    address: "903 W Parker Rd",
    city: "Plano",
    state: "TX",
    zip: "75023",
    latitude: 33.0411,
    longitude: -96.7135,
    website: "https://www.gracelifedallas.org/",
    zionistStance: "no",
    theologicalNotes: "Postmillennial eschatology. Reformed, covenant theology. Non-Zionist by theological conviction.",
    description: "Reformed church in the Dallas metro area committed to postmillennial, covenantal theology.",
    approved: true,
  },
  {
    name: "Christ Covenant Reformed Presbyterian Church",
    denomination: "RPCGA",
    address: "702 Business Way",
    city: "Wylie",
    state: "TX",
    zip: "75098",
    latitude: 33.0092,
    longitude: -96.5518,
    website: "https://www.christcovenantrpc.org/",
    phone: "(214) 799-1647",
    zionistStance: "no",
    theologicalNotes: "RPCGA denomination explicitly forbids dispensationalism in its Book of Church Order. Westminster Confession of Faith 1647. Institutionally non-Zionist.",
    description: "A particular church of the Reformed Presbyterian Church General Assembly, member of New Geneva Presbytery.",
    approved: true,
  },
  {
    name: "Brainerd Hills Presbyterian Church",
    denomination: "RPCGA",
    address: "6488 East Brainerd Rd",
    city: "Chattanooga",
    state: "TN",
    zip: "37421",
    latitude: 35.0179,
    longitude: -85.1941,
    website: "https://brainerdhills.org/",
    phone: "(423) 892-5308",
    zionistStance: "no",
    theologicalNotes: "RPCGA member — denomination explicitly forbids dispensationalism. Westminster Confession 1647. Institutionally non-Zionist.",
    description: "RPCGA church in Chattanooga. Member of Westminster Presbytery.",
    approved: true,
  },
  {
    name: "Reformation Presbyterian Church",
    denomination: "RPCGA",
    address: "3629 County Road V",
    city: "Sheboygan",
    state: "WI",
    zip: "53082",
    latitude: 43.6739,
    longitude: -87.7558,
    website: "https://www.reformationpc.org/",
    phone: "(920) 912-6501",
    zionistStance: "no",
    theologicalNotes: "RPCGA member — denomination explicitly forbids dispensationalism. Westminster Confession. Gospel-oriented and confessional.",
    description: "RPCGA church in Sheboygan. Gospel-oriented, confessional, and family-friendly.",
    approved: true,
  },
]

async function main() {
  console.log('Seeding database...')

  await prisma.report.deleteMany()
  await prisma.church.deleteMany()

  for (const church of churches) {
    await prisma.church.create({ data: church })
  }

  console.log(`Seeded ${churches.length} churches.`)
}

main()
  .catch(e => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
