import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const churches = [
  {
    name: "Grace Community Church",
    denomination: "Non-Denominational",
    address: "13248 Roscoe Blvd",
    city: "Sun Valley",
    state: "CA",
    zip: "91352",
    latitude: 34.2547,
    longitude: -118.3962,
    zionistStance: "yes",
    theologicalNotes: "Dispensational premillennialism. Strong Israel-support teaching.",
    description: "A large evangelical church known for biblical exposition and commitment to sound doctrine.",
    approved: true,
  },
  {
    name: "Founders Baptist Church",
    denomination: "Southern Baptist",
    address: "24724 Aldine Westfield Rd",
    city: "Spring",
    state: "TX",
    zip: "77373",
    latitude: 30.0799,
    longitude: -95.3863,
    zionistStance: "no",
    theologicalNotes: "Reformed Baptist, 1689 Confession. Covenantal theology, postmillennial leanings.",
    description: "A Reformed Baptist church focused on the doctrines of grace and expository preaching.",
    approved: true,
  },
  {
    name: "Apologia Church",
    denomination: "Reformed Baptist",
    address: "2024 S Arizona Ave",
    city: "Mesa",
    state: "AZ",
    zip: "85210",
    latitude: 33.3942,
    longitude: -111.8413,
    zionistStance: "anti",
    theologicalNotes: "Postmillennial, theonomic. Pastor Jeff Durbin stated it is 'insulting' to think modern Israel is God's chosen people. Posted on X: 'People who reject Christ are explicitly named as not being Israel.' Apologia Studios 'stand against Christian Zionists.' Publicly rebuked by Dr. Michael Brown for his anti-Zionist views.",
    description: "Known for apologetics ministry, committed to Reformed theology and cultural engagement.",
    approved: true,
  },
  {
    name: "Covenant Baptist Church",
    denomination: "Reformed Baptist",
    address: "5440 SW 37th St",
    city: "Topeka",
    state: "KS",
    zip: "66614",
    latitude: 38.9817,
    longitude: -95.7376,
    zionistStance: "no",
    theologicalNotes: "1689 Federalism. Covenantal, amillennial. No distinction between Israel and the Church.",
    description: "A confessional Reformed Baptist church committed to the 1689 London Baptist Confession of Faith.",
    approved: true,
  },
  {
    name: "Christ Fellowship Baptist Church",
    denomination: "Southern Baptist",
    address: "5100 S US Highway 17/92",
    city: "Casselberry",
    state: "FL",
    zip: "32707",
    latitude: 28.6614,
    longitude: -81.3275,
    zionistStance: "yes",
    theologicalNotes: "Dispensational. Teaches a distinct future for national Israel.",
    description: "A gospel-centered church focused on biblical preaching and community outreach in central Florida.",
    approved: true,
  },
  {
    name: "Cornerstone Church",
    denomination: "Non-Denominational",
    address: "18755 Stone Oak Pkwy",
    city: "San Antonio",
    state: "TX",
    zip: "78258",
    latitude: 29.6120,
    longitude: -98.4861,
    zionistStance: "yes",
    theologicalNotes: "Strongly dispensational. Hosts annual pro-Israel events. CUFI affiliated.",
    description: "A large evangelical church with a strong emphasis on biblical teaching and support for Israel.",
    approved: true,
  },
  {
    name: "McLean Bible Church",
    denomination: "Non-Denominational",
    address: "8925 Leesburg Pike",
    city: "Vienna",
    state: "VA",
    zip: "22182",
    latitude: 38.9121,
    longitude: -77.2270,
    zionistStance: "unknown",
    theologicalNotes: "Evangelical megachurch. Zionist stance not prominently stated.",
    description: "An evangelical megachurch in the Washington D.C. area focused on biblical teaching and community impact.",
    approved: true,
  },
  {
    name: "Heritage Baptist Church",
    denomination: "Independent Baptist",
    address: "14510 Sperry Rd",
    city: "Newbury",
    state: "OH",
    zip: "44065",
    latitude: 41.4633,
    longitude: -81.2191,
    zionistStance: "yes",
    theologicalNotes: "Traditional dispensational. KJV-preferred.",
    description: "A traditional Baptist church holding to conservative, biblical values in northeast Ohio.",
    approved: true,
  },
  {
    name: "Trinity Bible Church",
    denomination: "Non-Denominational",
    address: "2002 E 8th St",
    city: "Dallas",
    state: "TX",
    zip: "75203",
    latitude: 32.7724,
    longitude: -96.7770,
    zionistStance: "no",
    theologicalNotes: "Covenantal Reformed. Amillennial eschatology. Church = true Israel.",
    description: "A church committed to verse-by-verse Bible teaching and Reformed theology in Dallas.",
    approved: true,
  },
  {
    name: "Capitol Hill Baptist Church",
    denomination: "Southern Baptist",
    address: "525 A St NE",
    city: "Washington",
    state: "DC",
    zip: "20002",
    latitude: 38.8893,
    longitude: -77.0020,
    zionistStance: "unknown",
    theologicalNotes: "9Marks affiliated. Focus on ecclesiology over eschatology. Zionist stance not emphasized.",
    description: "Known for commitment to expository preaching, meaningful church membership, and biblical church leadership.",
    approved: true,
  },
  {
    name: "First Baptist Dallas",
    denomination: "Southern Baptist",
    address: "1707 San Jacinto St",
    city: "Dallas",
    state: "TX",
    zip: "75201",
    latitude: 32.7837,
    longitude: -96.7981,
    zionistStance: "yes",
    theologicalNotes: "Dispensational premillennial. Vocal support for Israel from leadership.",
    description: "A historic Southern Baptist church in downtown Dallas with a commitment to biblical authority.",
    approved: true,
  },
  {
    name: "Community Bible Church",
    denomination: "Non-Denominational",
    address: "2477 N Loop 1604 W",
    city: "San Antonio",
    state: "TX",
    zip: "78248",
    latitude: 29.5850,
    longitude: -98.5290,
    zionistStance: "yes",
    theologicalNotes: "Dispensational. Teaches pre-tribulation rapture and Israel's prophetic role.",
    description: "A Bible-teaching church focused on making disciples and serving the San Antonio community.",
    approved: true,
  },
  {
    name: "Providence Church",
    denomination: "Presbyterian (PCA)",
    address: "6014 Oleander Dr",
    city: "Wilmington",
    state: "NC",
    zip: "28403",
    latitude: 34.1985,
    longitude: -77.8865,
    zionistStance: "no",
    theologicalNotes: "Confessional Presbyterian. Westminster Standards. Covenantal amillennialism.",
    description: "A Presbyterian church in the PCA tradition with a focus on Reformed worship and teaching.",
    approved: true,
  },
  {
    name: "Redeemer Church",
    denomination: "Southern Baptist",
    address: "3075 Old Alabama Rd",
    city: "Alpharetta",
    state: "GA",
    zip: "30022",
    latitude: 34.0467,
    longitude: -84.2383,
    zionistStance: "unknown",
    theologicalNotes: "Reformed soteriology. Eschatological stance not prominently taught.",
    description: "A gospel-centered church committed to Reformed theology and community engagement in metro Atlanta.",
    approved: true,
  },
  {
    name: "Bethlehem Baptist Church",
    denomination: "Baptist General Conference",
    address: "720 13th Ave S",
    city: "Minneapolis",
    state: "MN",
    zip: "55415",
    latitude: 44.9669,
    longitude: -93.2589,
    zionistStance: "no",
    theologicalNotes: "Historic premillennial but not dispensational. Does not hold to Christian Zionism.",
    description: "A historic church known for its commitment to joyful theology and global missions.",
    approved: true,
  },
  // ── New non-Zionist churches ──
  {
    name: "Refuge Church",
    denomination: "Reformed",
    address: "607 26th Street",
    city: "Ogden",
    state: "UT",
    zip: "84401",
    latitude: 41.2184,
    longitude: -111.9647,
    website: "https://www.refugeutah.org/",
    zionistStance: "anti",
    theologicalNotes: "Confessionally Reformed — elders subscribe to Westminster Confession or 1689 LBCF. Postmillennial leanings. Covenant theology rejects dispensationalism. Pastors Brian Sauve and Eric Conn are vocal critics of Christian Zionism on X.",
    description: "Reformed church in Ogden led by a plurality of pastor/elders. Self-described 'jovial Calvinists' practicing baptismal catholicity.",
    approved: true,
  },
  {
    name: "Covenant Bible Church",
    denomination: "Reformed Baptist",
    address: "13470 E State Highway 29, Suite 100",
    city: "Georgetown",
    state: "TX",
    zip: "78626",
    latitude: 30.6351,
    longitude: -97.4765,
    website: "https://covenantbible.org/",
    phone: "(469) 487-6298",
    zionistStance: "anti",
    theologicalNotes: "1689 LBCF. Postmillennial, general equity theonomy. Pastor Joel Webbon (Right Response Ministries) is vocally anti-Zionist and anti-dispensationalist. Christian Reconstructionist influence.",
    description: "A Bible-believing, Bible-preaching church in the Austin metro area. Affiliated with Right Response Ministries.",
    approved: true,
  },
  {
    name: "Christ Church",
    denomination: "CREC",
    address: "820 Dominion Way",
    city: "Moscow",
    state: "ID",
    zip: "83843",
    latitude: 46.7317,
    longitude: -117.0028,
    website: "https://christkirk.com/",
    phone: "(208) 882-2034",
    zionistStance: "anti",
    theologicalNotes: "Postmillennial, covenant theology, Calvinist. Doug Wilson is one of the most prominent voices against dispensationalism in American Christianity. Explicitly rejects Christian Zionism as theological error.",
    description: "Flagship church of the CREC denomination and center of the Moscow, Idaho Reformed community. ~3,000 members. Associated with New Saint Andrews College and Canon Press.",
    approved: true,
  },
  {
    name: "Dominion Covenant Church",
    denomination: "CPC (Presbyterian)",
    address: "6104 Irvington Road",
    city: "Omaha",
    state: "NE",
    zip: "68134",
    latitude: 41.3143,
    longitude: -96.0527,
    website: "https://dominioncovenantchurch.com/",
    phone: "(402) 819-9953",
    zionistStance: "anti",
    theologicalNotes: "Theonomic, postmillennial, Reformed. Dr. Phillip Kayser is a prominent theonomist. Covenant theology is foundational — actively anti-Zionist/anti-dispensationalist.",
    description: "Mission: 'Promoting and enjoying the dominion of King Jesus over every area of life.' Founded by Dr. Phillip Kayser.",
    approved: true,
  },
  {
    name: "King's Way Reformed Church",
    denomination: "Reformed",
    address: "1100 E Sheldon St",
    city: "Prescott",
    state: "AZ",
    zip: "86301",
    latitude: 34.5452,
    longitude: -112.4559,
    website: "https://kingswaybible.org/",
    zionistStance: "anti",
    theologicalNotes: "Postmillennial, general equity theonomy. Westminster Confession. Pastor Dale Partridge (Reformation Seminary) is outspokenly anti-Zionist and anti-dispensationalist.",
    description: "A Reformed church plant in Prescott raising up Gospel-fluent families. Dale Partridge also founded Reformation Seminary.",
    approved: true,
  },
  {
    name: "Trinity Church",
    denomination: "CREC",
    address: "720 E Poplar Ave",
    city: "Coeur d'Alene",
    state: "ID",
    zip: "83814",
    latitude: 47.6921,
    longitude: -116.7759,
    website: "https://trinitycda.org/",
    phone: "(208) 615-5075",
    zionistStance: "no",
    theologicalNotes: "CREC church — covenant theology, Reformed soteriology. Rejects dispensationalism. Part of the broader Idaho Reformed community.",
    description: "CREC church in northern Idaho, part of the broader Moscow/Idaho Reformed community. Worshiping together since 2006.",
    approved: true,
  },
  {
    name: "Christ Church Spokane",
    denomination: "CREC",
    address: "228 E Gordon Ave",
    city: "Spokane",
    state: "WA",
    zip: "99207",
    latitude: 47.6907,
    longitude: -117.4070,
    website: "https://ccspokane.com/",
    phone: "(509) 329-0314",
    zionistStance: "no",
    theologicalNotes: "CREC member — covenant theology, Reformed. Rejects dispensationalism. Non-Zionist by covenantal conviction.",
    description: "CREC church in Spokane serving the inland Northwest Reformed community.",
    approved: true,
  },
  {
    name: "Reformation Covenant Church",
    denomination: "CREC",
    address: "1201 JQ Adams St",
    city: "Oregon City",
    state: "OR",
    zip: "97045",
    latitude: 45.3579,
    longitude: -122.5972,
    website: "https://reformationcovenant.org/",
    phone: "(503) 656-9444",
    zionistStance: "no",
    theologicalNotes: "CREC member — covenant theology, Reformed. Rejects dispensationalism. Established 1983, deep roots in Reformation theology.",
    description: "One of the older CREC congregations, worshiping, learning, and doing life together since 1983.",
    approved: true,
  },
  {
    name: "The Shepherd's Church",
    denomination: "CREC",
    address: "10 Jean Ave, Suite 12",
    city: "Chelmsford",
    state: "MA",
    zip: "01824",
    latitude: 42.6222,
    longitude: -71.3597,
    website: "https://www.theshepherds.church/",
    phone: "(978) 304-6265",
    zionistStance: "anti",
    theologicalNotes: "CREC member. Reformed, confessional, family-integrated. Pastor Kendall Lankford hosts 'The PRODCAST' with a series titled 'Why Zionism Breaks Christian Theology' — actively opposes Christian Zionism.",
    description: "Founded in 2019. A reformed, confessional, family-integrated church serving the Chelmsford/Lowell area of Massachusetts.",
    approved: true,
  },
  {
    name: "Providence Church Pensacola",
    denomination: "CREC",
    address: "9600 N Palafox St",
    city: "Pensacola",
    state: "FL",
    zip: "32534",
    latitude: 30.5362,
    longitude: -87.2752,
    website: "https://www.providencepensacola.org/",
    phone: "(850) 377-3049",
    zionistStance: "no",
    theologicalNotes: "CREC member. Westminster Confession of Faith (1646) and Heidelberg Catechism. Robustly Calvinistic and covenantal. Rejects dispensationalism.",
    description: "CREC church led by Rev. Dr. Uriesou Brito. Moved to new property in January 2026 after 17+ years at Trinitas Christian School.",
    approved: true,
  },
  {
    name: "Holy Trinity Reformed Church",
    denomination: "CREC",
    address: "3747 Trinity Church Road",
    city: "Concord",
    state: "NC",
    zip: "28027",
    latitude: 35.4655,
    longitude: -80.6881,
    website: "http://www.htrchurch.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Rejects dispensationalism. Non-Zionist by covenantal conviction.",
    description: "CREC church in the Charlotte metro area of North Carolina.",
    approved: true,
  },
  {
    name: "Christ the King Church",
    denomination: "CREC",
    address: "1223 Grove Road",
    city: "Greenville",
    state: "SC",
    zip: "29605",
    latitude: 34.8071,
    longitude: -82.4218,
    website: "http://www.christkingchurch.com/",
    phone: "(864) 202-6920",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Affirms ecumenical creeds. Rejects dispensationalism.",
    description: "CREC church in Greenville, SC. Affirms the ecumenical creeds and Reformed theology.",
    approved: true,
  },
  {
    name: "Providence Church Lynchburg",
    denomination: "CREC",
    address: "108 Melinda Dr",
    city: "Lynchburg",
    state: "VA",
    zip: "24502",
    latitude: 37.3450,
    longitude: -79.1935,
    website: "https://www.providencekirk.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Rejects dispensationalism. Founded as home Bible study in 2000.",
    description: "CREC church in Lynchburg, Virginia. Founded by Pastor Virgil Hurt in December 2000.",
    approved: true,
  },
  {
    name: "Trinity Church Kirkland",
    denomination: "CREC",
    address: "6400 108th Ave NE",
    city: "Kirkland",
    state: "WA",
    zip: "98033",
    latitude: 47.6639,
    longitude: -122.1961,
    website: "https://trinitykirk.org/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology. Rejects dispensationalism. Serves the Seattle metro eastside.",
    description: "CREC church in the Seattle metro area serving the eastside communities.",
    approved: true,
  },
  {
    name: "Tri-City Covenant Church",
    denomination: "CREC",
    address: "150 West High Street",
    city: "Somersworth",
    state: "NH",
    zip: "03878",
    latitude: 43.2605,
    longitude: -70.8885,
    website: "https://tricitycovenant.com/",
    phone: "(603) 692-2093",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformational Catholic identity. Covenant theology rejects dispensationalism.",
    description: "A Reformational Catholic church serving Somersworth, Rochester, and Dover, New Hampshire. Joined CREC in 2008.",
    approved: true,
  },
  {
    name: "Phoenix Reformed Baptist Church",
    denomination: "Reformed Baptist",
    address: "3805 N 12th St",
    city: "Phoenix",
    state: "AZ",
    zip: "85014",
    latitude: 33.4912,
    longitude: -112.0563,
    website: "https://prbc.org/",
    phone: "(602) 264-7223",
    zionistStance: "no",
    theologicalNotes: "Reformed Baptist, 1689 framework. Postmillennial leanings. Covenant theology rejects dispensationalism.",
    description: "A Reformed Baptist fellowship emphasizing worship through prayer and consistent, in-depth proclamation of Scripture.",
    approved: true,
  },
  {
    name: "Grace Life Church of Dallas",
    denomination: "Reformed",
    address: "903 W Parker Rd",
    city: "Plano",
    state: "TX",
    zip: "75023",
    latitude: 33.0411,
    longitude: -96.7135,
    website: "https://www.gracelifedallas.org/",
    zionistStance: "no",
    theologicalNotes: "Postmillennial eschatology. Reformed, covenant theology. Non-Zionist by theological conviction.",
    description: "Reformed church in the Dallas metro area committed to postmillennial, covenantal theology.",
    approved: true,
  },
  {
    name: "Christ Covenant Reformed Presbyterian Church",
    denomination: "RPCGA",
    address: "702 Business Way",
    city: "Wylie",
    state: "TX",
    zip: "75098",
    latitude: 33.0092,
    longitude: -96.5518,
    website: "https://www.christcovenantrpc.org/",
    phone: "(214) 799-1647",
    zionistStance: "no",
    theologicalNotes: "RPCGA denomination explicitly forbids dispensationalism in its Book of Church Order. Westminster Confession of Faith 1647. Institutionally non-Zionist.",
    description: "A particular church of the Reformed Presbyterian Church General Assembly, member of New Geneva Presbytery.",
    approved: true,
  },
  {
    name: "Brainerd Hills Presbyterian Church",
    denomination: "RPCGA",
    address: "6488 East Brainerd Rd",
    city: "Chattanooga",
    state: "TN",
    zip: "37421",
    latitude: 35.0179,
    longitude: -85.1941,
    website: "https://brainerdhills.org/",
    phone: "(423) 892-5308",
    zionistStance: "no",
    theologicalNotes: "RPCGA member — denomination explicitly forbids dispensationalism. Westminster Confession 1647. Institutionally non-Zionist.",
    description: "RPCGA church in Chattanooga. Member of Westminster Presbytery.",
    approved: true,
  },
  {
    name: "Reformation Presbyterian Church",
    denomination: "RPCGA",
    address: "3629 County Road V",
    city: "Sheboygan",
    state: "WI",
    zip: "53082",
    latitude: 43.6739,
    longitude: -87.7558,
    website: "https://www.reformationpc.org/",
    phone: "(920) 912-6501",
    zionistStance: "no",
    theologicalNotes: "RPCGA member — denomination explicitly forbids dispensationalism. Westminster Confession. Gospel-oriented and confessional.",
    description: "RPCGA church in Sheboygan. Gospel-oriented, confessional, and family-friendly.",
    approved: true,
  },
  // ── New anti-Zionist churches ──
  {
    name: "Liberty Fellowship",
    denomination: "Non-Denominational",
    address: "1140 US Highway 2 W",
    city: "Kalispell",
    state: "MT",
    zip: "59901",
    latitude: 48.1980,
    longitude: -114.3160,
    website: "https://libertyfellowshipmt.com/",
    zionistStance: "anti",
    theologicalNotes: "Pastor Chuck Baldwin (former Constitution Party presidential candidate) has called Christian Zionism 'the most dangerous and devilish' prophetic interpretation. Publicly named John Hagee, Robert Jeffress, and John MacArthur as false teachers on Zionism. Featured on WHTT Podcast: 'How Pastor Chuck Baldwin Came Out of the Bondage of Christian Zionism.'",
    description: "Independent non-501(c)(3) fellowship led by Dr. Chuck Baldwin. Known for combining constitutional patriotism with anti-Zionist theology.",
    approved: true,
  },
  {
    name: "Word of Life Church",
    denomination: "Non-Denominational",
    address: "3902 NE Riverside Rd",
    city: "Saint Joseph",
    state: "MO",
    zip: "64505",
    latitude: 39.7870,
    longitude: -94.7900,
    website: "https://wolc.com/",
    phone: "(816) 233-6367",
    zionistStance: "anti",
    theologicalNotes: "Pastor Brian Zahnd was a prominent speaker at Christ at the Checkpoint (anti-Zionist conference in Bethlehem). Stated: 'American Christians are not called to take Israel's side. They're called to imitate Israel's Messiah.' Lost nearly half his congregation (~1,000 members) when he publicly rejected Christian Zionism.",
    description: "A church in Saint Joseph, MO led by Pastor Brian Zahnd, known for challenging Christian Zionism and advocating for Palestinian justice.",
    approved: true,
  },
  // ── New churches for uncovered states ──
  // Alabama (AL)
  {
    name: "Trinity Presbyterian Church",
    denomination: "CREC",
    address: "7160 Cahaba Valley Road",
    city: "Birmingham",
    state: "AL",
    zip: "35242",
    latitude: 33.3770,
    longitude: -86.7370,
    website: "https://trinitypresbham.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Rich Lusk — covenant theology, postmillennial, Federal Vision. Rejects dispensationalism. 20+ year pastorate.",
    description: "CREC church in Birmingham led by theologian Rich Lusk. Known for covenant theology and liturgical worship.",
    approved: true,
  },
  // Alaska (AK)
  {
    name: "Covenant Bible Church",
    denomination: "CREC",
    address: "745 W Auklet Ave",
    city: "Palmer",
    state: "AK",
    zip: "99645",
    latitude: 61.5994,
    longitude: -149.1127,
    website: "https://www.covenantbiblechurch.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member since 2004. Pastor Jack Phelps — covenant theology, Reformed. Former presiding minister of the CREC nationally. Rejects dispensationalism.",
    description: "Founded in 1958. CREC congregation in south-central Alaska. Pastor Phelps is an Air Force veteran and former adviser to four Alaska governors.",
    approved: true,
  },
  // Arkansas (AR)
  {
    name: "Christ Church Searcy",
    denomination: "CREC",
    address: "3390 AR-36",
    city: "Searcy",
    state: "AR",
    zip: "72143",
    latitude: 35.2620,
    longitude: -91.7351,
    website: "https://christchurchsearcy.com/",
    phone: "(501) 777-3197",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed, covenant theology, biblical liturgy. Rejects dispensationalism. Mission church of Four Winds Reformed Church (CREC).",
    description: "A community of Christians in Searcy called to Christ through the power of the gospel. Liturgical worship Sundays at 10:30 AM.",
    approved: true,
  },
  // California (CA) — non-Zionist addition
  {
    name: "Christ Church Santa Clarita",
    denomination: "CREC",
    address: "24436 Valley Street",
    city: "Newhall",
    state: "CA",
    zip: "91321",
    latitude: 34.3853,
    longitude: -118.5310,
    website: "https://www.christchurchscv.com/",
    phone: "(661) 373-1760",
    zionistStance: "no",
    theologicalNotes: "CREC member. Confessionally Reformed, covenant theology. Founded in 2007. Rejects dispensationalism.",
    description: "A confessional Reformed church in the Santa Clarita Valley serving northern Los Angeles County.",
    approved: true,
  },
  // Colorado (CO)
  {
    name: "Christ Church Denver",
    denomination: "CREC",
    address: "3595 W Belleview Ave",
    city: "Englewood",
    state: "CO",
    zip: "80110",
    latitude: 39.6447,
    longitude: -105.0108,
    website: "https://christkirkdenver.church",
    zionistStance: "no",
    theologicalNotes: "CREC member. Reformed and Evangelical. Covenant renewal worship with weekly communion. Rejects dispensationalism.",
    description: "CREC church in the Denver metro area. Weekly Lord's Day Covenant Renewal Worship Service.",
    approved: true,
  },
  // Connecticut (CT)
  {
    name: "Covenant Presbyterian Church",
    denomination: "PCA",
    address: "1 Fairway Drive",
    city: "Ledyard",
    state: "CT",
    zip: "06339",
    latitude: 41.4398,
    longitude: -72.0119,
    website: "https://ledyardpca.org/",
    phone: "(860) 464-8476",
    zionistStance: "no",
    theologicalNotes: "PCA church. Westminster Standards. Confessional Reformed theology, covenant theology. Pastor Rodney Henderson since 2013. Rejects dispensationalism.",
    description: "A Bible-based Reformed PCA church in historic Ledyard Center, Connecticut.",
    approved: true,
  },
  // Delaware (DE)
  {
    name: "Emmanuel Presbyterian Church",
    denomination: "OPC",
    address: "1006 Wilson Rd",
    city: "Wilmington",
    state: "DE",
    zip: "19803",
    latitude: 39.7912,
    longitude: -75.5643,
    website: "https://eopc.org/",
    phone: "(302) 478-7776",
    zionistStance: "no",
    theologicalNotes: "OPC church. Westminster Standards. Confessional Reformed theology. Pastor David Landow. Rejects dispensationalism by confessional commitment.",
    description: "An Orthodox Presbyterian Church congregation devoted to honoring God and serving Him according to the Bible's teachings.",
    approved: true,
  },
  // Hawaii (HI)
  {
    name: "Redeemer Reformed Church",
    denomination: "OPC",
    address: "94-235 Hanawai Circle, Unit 9",
    city: "Waipahu",
    state: "HI",
    zip: "96797",
    latitude: 21.3820,
    longitude: -158.0117,
    website: "https://www.redeemerhawaii.org/",
    phone: "(310) 738-1507",
    zionistStance: "no",
    theologicalNotes: "OPC church. Westminster Standards. Pastor Eli Hirtzel (MDiv, Westminster Theological Seminary). Multi-ethnic congregation. Rejects dispensationalism by confessional commitment.",
    description: "A multi-ethnic beacon of Biblical, Reformed Christianity on the island of Oahu.",
    approved: true,
  },
  // Illinois (IL)
  {
    name: "Christ Covenant Church of Chicago",
    denomination: "CREC",
    address: "2720 Kirchoff Road",
    city: "Rolling Meadows",
    state: "IL",
    zip: "60008",
    latitude: 42.0765,
    longitude: -88.0132,
    website: "https://www.christcovenantchicago.org/",
    phone: "(847) 348-9980",
    zionistStance: "no",
    theologicalNotes: "CREC member (Tyndale Presbytery). Pastor Jon Herr. Covenant Renewal Worship with weekly communion. Historic Reformed faith. Rejects dispensationalism.",
    description: "CREC church in the Chicago suburbs committed to Covenant Renewal Worship and historic Reformed Christianity.",
    approved: true,
  },
  // Indiana (IN)
  {
    name: "Christ Church Indy",
    denomination: "CREC",
    address: "849 W 96th St",
    city: "Indianapolis",
    state: "IN",
    zip: "46260",
    latitude: 39.9177,
    longitude: -86.1773,
    website: "https://christchurchindy.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member (Tyndale Presbytery). Reformed and covenantally oriented. Plurality of elders. Protestant catholicity — accepts believers across denominational lines. Rejects dispensationalism.",
    description: "A reformed and covenantally-oriented church in the Indianapolis metro area, practicing passage-by-passage preaching.",
    approved: true,
  },
  // Iowa (IA)
  {
    name: "Christ the Redeemer Church",
    denomination: "CREC",
    address: "2485 IA-163",
    city: "Pella",
    state: "IA",
    zip: "50219",
    latitude: 41.4089,
    longitude: -92.9168,
    website: "https://redeemerpella.org/",
    phone: "(877) 668-4442",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Michael Shover — postmillennial, covenant theology, Christian nationalist. Rejects dispensationalism. Ordained 2018.",
    description: "CREC church in Pella, Iowa. Led by Pastor Michael Shover.",
    approved: true,
  },
  // Kentucky (KY)
  {
    name: "Reformed Baptist Church of Louisville",
    denomination: "Reformed Baptist",
    address: "3400 Wilderness Trail",
    city: "Louisville",
    state: "KY",
    zip: "40299",
    latitude: 38.1787,
    longitude: -85.5522,
    website: "https://rbclouisville.com/",
    phone: "(502) 266-6573",
    zionistStance: "no",
    theologicalNotes: "1689 London Baptist Confession of Faith. Pastor Jim Savastio (25+ years). Covenant theology, Reformed soteriology. Rejects dispensationalism.",
    description: "A confessional Reformed Baptist church in Louisville committed to biblical, historical, practical, God-centered Christianity.",
    approved: true,
  },
  // Louisiana (LA)
  {
    name: "All Saints Reformed Church",
    denomination: "CREC",
    address: "434 Lamarque St",
    city: "Mandeville",
    state: "LA",
    zip: "70448",
    latitude: 30.3585,
    longitude: -90.0836,
    website: "https://allsaintsreformed.world/",
    phone: "(985) 237-8620",
    zionistStance: "no",
    theologicalNotes: "CREC mission church. Pastor Kent Bergeron. Reformed Evangelical, covenant theology. Rejects dispensationalism.",
    description: "CREC mission church on the north shore of Lake Pontchartrain, Louisiana.",
    approved: true,
  },
  // Maine (ME)
  {
    name: "Christ Reformed Church",
    denomination: "CREC",
    address: "107 Belgrade Ave",
    city: "Oakland",
    state: "ME",
    zip: "04963",
    latitude: 44.5406,
    longitude: -69.7220,
    website: "https://www.crcmaine.church/",
    phone: "(207) 619-4517",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Chris Boland, Associate Pastor Grant Van Brimmer. Biblical liturgical worship, covenant theology. Rejects dispensationalism.",
    description: "CREC church in central Maine focused on biblical liturgical worship, genuine community, and discipleship.",
    approved: true,
  },
  // Maryland (MD)
  {
    name: "Christ Reformed Evangelical Church",
    denomination: "CREC",
    address: "1841 Generals Highway",
    city: "Annapolis",
    state: "MD",
    zip: "21401",
    latitude: 38.9729,
    longitude: -76.5469,
    website: "https://crecannapolis.com/",
    phone: "(443) 494-9544",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Dan Nash. Covenant Renewal Service with weekly communion. Upholds historic Christian creeds and Reformation confessions. Rejects dispensationalism.",
    description: "CREC church in Annapolis, Maryland. Covenant Renewal worship with services at 8:30 AM and 10:30 AM.",
    approved: true,
  },
  // Michigan (MI)
  {
    name: "Christ Church of Livingston County",
    denomination: "CREC",
    address: "114 S Walnut St",
    city: "Howell",
    state: "MI",
    zip: "48843",
    latitude: 42.6078,
    longitude: -83.9314,
    website: "https://christkirkmi.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member (Tyndale Presbytery). Founded 2003. Covenant theology, Reformed. Kendall Lankford has preached here. Rejects dispensationalism.",
    description: "CREC mission church in historic downtown Howell, Michigan. Worship Sundays at 10 AM.",
    approved: true,
  },
  // Mississippi (MS)
  {
    name: "Immanuel Presbyterian Church",
    denomination: "CREC",
    address: "1702 Old Vicksburg Rd",
    city: "Clinton",
    state: "MS",
    zip: "39056",
    latitude: 32.3465,
    longitude: -90.3365,
    website: "https://ipcclinton.org/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor George Garrison (since 2008). Reformed, covenant theology. Rejects dispensationalism.",
    description: "CREC church in Clinton, Mississippi serving the Jackson metro area. Founded 2006.",
    approved: true,
  },
  // Nevada (NV)
  {
    name: "Christ Church Las Vegas",
    denomination: "CREC",
    address: "2004 N Spring Gate Ln",
    city: "Las Vegas",
    state: "NV",
    zip: "89134",
    latitude: 36.2032,
    longitude: -115.2886,
    website: "https://christchurchlasvegas.com/",
    phone: "(702) 721-7504",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Jeff Stackhouse. Covenant renewal liturgy with weekly communion. Reformed, covenant theology. Rejects dispensationalism.",
    description: "CREC church in Las Vegas, Nevada. Covenant renewal worship Sundays at 1:30 PM.",
    approved: true,
  },
  // New Jersey (NJ)
  {
    name: "Reformed Baptist Church of Lafayette",
    denomination: "Reformed Baptist",
    address: "29 Morris Farm Rd",
    city: "Lafayette",
    state: "NJ",
    zip: "07848",
    latitude: 41.0959,
    longitude: -74.6879,
    website: "https://rbcl.church/",
    zionistStance: "no",
    theologicalNotes: "1689 London Baptist Confession. Both Reformed and Baptistic. Covenant theology. Rejects dispensationalism.",
    description: "A Reformed Baptist church in rural New Jersey committed to whole-hearted obedience to God's Word in worship, evangelism, and discipleship.",
    approved: true,
  },
  // New Mexico (NM)
  {
    name: "Redeemer Reformed Church",
    denomination: "OPC",
    address: "1771 Rio Rancho Blvd SE",
    city: "Rio Rancho",
    state: "NM",
    zip: "87124",
    latitude: 35.2542,
    longitude: -106.6601,
    website: "https://rropc.org/",
    phone: "(843) 812-6701",
    zionistStance: "no",
    theologicalNotes: "OPC church. Pastor Todd Bordow (MDiv, Westminster Seminary California) — notably a Jewish convert to Christianity. Westminster Standards, Reformed doctrine, Presbyterian government. Rejects dispensationalism.",
    description: "OPC church in Rio Rancho, NM (adjacent to Albuquerque). Founded 2007. Led by a Jewish convert to the Christian faith.",
    approved: true,
  },
  // New York (NY)
  {
    name: "The King's Chapel",
    denomination: "CREC",
    address: "2702 Quentin Rd",
    city: "Brooklyn",
    state: "NY",
    zip: "11229",
    latitude: 40.6003,
    longitude: -73.9472,
    website: "https://kingschapelnyc.org/",
    phone: "(718) 415-8015",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Troy Greene. Founded 2010. Reformed, covenant theology. Rejects dispensationalism.",
    description: "CREC church in Brooklyn, New York. Worship Sundays at 10:00 AM followed by fellowship and Sunday School.",
    approved: true,
  },
  // North Dakota (ND)
  {
    name: "Bethel Orthodox Presbyterian Church",
    denomination: "OPC",
    address: "211 2nd Ave NW",
    city: "Mandan",
    state: "ND",
    zip: "58554",
    latitude: 46.8283,
    longitude: -100.8947,
    website: "https://www.bethelopc.net/",
    phone: "(701) 751-1107",
    zionistStance: "no",
    theologicalNotes: "OPC church. Pastor Bruce Prentice. Westminster Standards, confessional Reformed. Relocated from rural Carson to Mandan. Rejects dispensationalism.",
    description: "A Reformed Orthodox Presbyterian church serving the Bismarck-Mandan area of North Dakota.",
    approved: true,
  },
  // Ohio (OH) — non-Zionist addition
  {
    name: "All Souls Reformed Church",
    denomination: "CREC",
    address: "228 Main Street",
    city: "Green Camp",
    state: "OH",
    zip: "43322",
    latitude: 40.5332,
    longitude: -83.2182,
    website: "https://allsoulschurch.us/",
    phone: "(740) 528-2092",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Rhett Crabtree. Reformed, covenant theology. Rejects dispensationalism.",
    description: "CREC congregation in the historic red brick church on the corner of Route 739 and Main Street in Green Camp, Ohio.",
    approved: true,
  },
  // Oklahoma (OK)
  {
    name: "Redeemer Reformed Church",
    denomination: "CREC",
    address: "1300 N Robinson Ave",
    city: "Oklahoma City",
    state: "OK",
    zip: "73103",
    latitude: 35.4793,
    longitude: -97.5167,
    website: "https://redeemerokc.org/",
    phone: "(405) 601-2255",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Mark Balthrop. Evangelical and confessionally Reformed. Covenant theology. Rejects dispensationalism.",
    description: "An evangelical and confessionally Reformed CREC congregation in Oklahoma City seeking to proclaim the saving grace of God in Christ.",
    approved: true,
  },
  // Pennsylvania (PA)
  {
    name: "All Saints Church",
    denomination: "CREC",
    address: "276 West Main St",
    city: "New Holland",
    state: "PA",
    zip: "17557",
    latitude: 40.1011,
    longitude: -76.0849,
    website: "https://allsaints-church.com/",
    zionistStance: "no",
    theologicalNotes: "CREC member. Pastor Kasey Horvath (ordained 2023). Historic, Biblically grounded worship. Family-integrated. Rejects dispensationalism.",
    description: "A Reformed CREC congregation in Lancaster County, PA gathering in a historic church building for Covenant Renewal worship.",
    approved: true,
  },
  // Rhode Island (RI)
  {
    name: "Christ Reformed Presbyterian Church",
    denomination: "RPCNA",
    address: "10 Turner Ave",
    city: "East Providence",
    state: "RI",
    zip: "02915",
    latitude: 41.8451,
    longitude: -71.3629,
    website: "https://christrpc.com/",
    phone: "(401) 709-4678",
    zionistStance: "no",
    theologicalNotes: "RPCNA member. Pastor Daniel Howe. Reformed Presbyterian, Westminster Standards. Expository preaching, exclusive psalmody. Rejects dispensationalism.",
    description: "An RPCNA congregation in East Providence emphasizing expository preaching, congregational singing, and communal prayer.",
    approved: true,
  },
  // South Dakota (SD)
  {
    name: "Grace Reformed Church",
    denomination: "RCUS",
    address: "5626 Haines Ave",
    city: "Rapid City",
    state: "SD",
    zip: "57701",
    latitude: 44.0649,
    longitude: -103.2069,
    website: "https://gracereformedrapidcity.com/",
    phone: "(605) 399-1711",
    zionistStance: "no",
    theologicalNotes: "RCUS member. Pastor David Fagrey. Three Forms of Unity (Belgic Confession, Heidelberg Catechism, Canons of Dort). Continental Reformed. Rejects dispensationalism.",
    description: "An RCUS church in Rapid City committed to the five solas of the Reformation and the historic Reformed confessions.",
    approved: true,
  },
  // Vermont (VT)
  {
    name: "Covenant Orthodox Presbyterian Church",
    denomination: "OPC",
    address: "249 Airport Rd",
    city: "Barre",
    state: "VT",
    zip: "05641",
    latitude: 44.1906,
    longitude: -72.5026,
    website: "https://copcvt.org/",
    phone: "(802) 479-2010",
    zionistStance: "no",
    theologicalNotes: "OPC church. Pastor Carl Durham. Westminster Standards, confessional Reformed. Rejects dispensationalism by confessional commitment.",
    description: "The only OPC congregation in Vermont, serving the Barre-Montpelier area.",
    approved: true,
  },
  // West Virginia (WV)
  {
    name: "Christ Church of Morgantown",
    denomination: "CREC",
    address: "200 Trinity Way",
    city: "Morgantown",
    state: "WV",
    zip: "26505",
    latitude: 39.6296,
    longitude: -79.9559,
    website: "https://christchurchofmorgantown.org/",
    zionistStance: "no",
    theologicalNotes: "CREC member (Augustine Presbytery). Pastor Jared McNabb. Confessionally Reformed and Protestant. Covenant theology. Rejects dispensationalism.",
    description: "CREC church in Morgantown pursuing biblical community through a comprehensive application of God's Word. Worship Sundays at 10:30 AM.",
    approved: true,
  },
  // Wyoming (WY)
  {
    name: "Laramie Reformed Presbyterian Church",
    denomination: "RPCNA",
    address: "365 W Grand Ave",
    city: "Laramie",
    state: "WY",
    zip: "82072",
    latitude: 41.3114,
    longitude: -105.5911,
    website: "https://laramierpc.org/",
    phone: "(307) 460-4321",
    zionistStance: "no",
    theologicalNotes: "RPCNA member. Pastor Allen Blackwood. Westminster Standards. Exclusive psalmody. Confessionally Reformed. Rejects dispensationalism.",
    description: "An RPCNA congregation in Laramie, Wyoming. Morning worship at 10:00 AM with Sunday School and occasional evening worship.",
    approved: true,
  },
  // ── Anti-Zionist addition ──
  {
    name: "Whitleyville Reformation Church",
    denomination: "Reformed",
    address: "Whitleyville",
    city: "Whitleyville",
    state: "TN",
    zip: "38588",
    latitude: 36.4317,
    longitude: -85.5117,
    website: "https://whitleyvillechurch.com/",
    zionistStance: "anti",
    theologicalNotes: "Pastor Andrew Isker — appeared on Tucker Carlson criticizing dispensationalism. Co-authored 'Christian Nationalism: A Biblical Guide to Taking Dominion.' Embraces supersessionism/replacement theology. Rejected 'Judeo-Christian' concept on Joel Webbon's podcast. Explicitly anti-Zionist.",
    description: "A Reformed church plant in rural Jackson County, Tennessee, part of the RidgeRunner Christian community. Founded by pastor and author Andrew Isker.",
    approved: true,
  },
  // ── Anti-Zionist churches found via pastor network analysis ──
  {
    name: "Christ the King Reformed Church",
    denomination: "Independent Reformed",
    address: "421 State St",
    city: "Charlotte",
    state: "MI",
    zip: "48813",
    latitude: 42.5636,
    longitude: -84.8358,
    website: "https://charlottereformed.org/",
    phone: "(517) 588-9129",
    zionistStance: "anti",
    theologicalNotes: "Pastor Bret McAtee (Kuyperian tradition). Wrote that dispensationalism 'served as the means by which we have been enslaved by Israel.' States 'Modern Israel is irrelevant to God's ongoing macro plan of redemption.' Hosts Iron Rhetoric podcast. Connected to Pactum Institute network.",
    description: "An independent Reformed church in Charlotte, Michigan in the Kuyperian tradition. Led by Pastor Bret McAtee.",
    approved: true,
  },
  {
    name: "Sovereign King Church",
    denomination: "Evangel Presbytery",
    address: "332 E Chestnut St",
    city: "Jeffersonville",
    state: "IN",
    zip: "47130",
    latitude: 38.2776,
    longitude: -85.7370,
    website: "https://sovereignkingchurch.com/",
    phone: "(502) 509-7819",
    zionistStance: "anti",
    theologicalNotes: "Pastor Joseph Spurgeon publicly refused to sign the Antioch Declaration (Nov 2024) and drafted the counter 'Statement on Natural Affections.' Describes 'Judeo-Christian' as a 20th-century construct. Positioned in the anti-Zionist faction of the Reformed network.",
    description: "A Reformed church in Jeffersonville, Indiana led by Pastor Joseph Spurgeon. Member of Evangel Presbytery.",
    approved: true,
  },
  {
    name: "The Well Church",
    denomination: "Reformed Baptist",
    address: "300 S Broadway",
    city: "Boulder",
    state: "CO",
    zip: "80305",
    latitude: 39.9866,
    longitude: -105.2598,
    website: "https://boulderwell.org/",
    phone: "(720) 583-5189",
    zionistStance: "anti",
    theologicalNotes: "Pastor J. Chase Davis wrote in The Federalist: 'For too many American Christians, misplaced theological convictions have led to political loyalties that prioritize Israel over both the church and their own nation.' Panelist at New Christendom Press Conference alongside Webbon, Sauve, and Conn.",
    description: "A Reformed church in Boulder, Colorado led by Pastor J. Chase Davis. Connected to the New Christendom Press network.",
    approved: true,
  },
  {
    name: "Bryce Avenue Presbyterian Church",
    denomination: "PCA",
    address: "333 Bryce Ave",
    city: "White Rock",
    state: "NM",
    zip: "87547",
    latitude: 35.8271,
    longitude: -106.2122,
    website: "https://brycepresbyterian.org/",
    phone: "(505) 672-3364",
    zionistStance: "anti",
    theologicalNotes: "Pastor Zachary Garris wrote in The Blaze: 'As a Christian, I have no special relationship to the modern nation-state of Israel.' Argues the Church is 'the Israel of God.' Published 'Honor Thy Fathers' through New Christendom Press (Sauve/Conn network). Contributor to American Reformer.",
    description: "A PCA church in White Rock, New Mexico led by Pastor Zachary Garris, author and contributor to American Reformer.",
    approved: true,
  },
]

async function main() {
  console.log('Seeding database...')

  await prisma.report.deleteMany()
  await prisma.church.deleteMany()

  for (const church of churches) {
    await prisma.church.create({ data: church })
  }

  console.log(`Seeded ${churches.length} churches.`)
}

main()
  .catch(e => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
