// Sample church data for the directory prototype
window.CHURCH_DATA = [
  { id: 1, name: "Albany Baptist Church", denomination: "Reformed Baptist", city: "Bethlehem", state: "NY", lat: 42.59, lng: -73.85, position: "anti-zionist", phone: "(518) 463-6364", website: true, founded: 1829, attendance: 220, blurb: "A Reformed Baptist church committed to biblical, confessional Christianity. Holds to the 1689 London Baptist Confession.", pastor: "Rev. James Whitfield" },
  { id: 2, name: "Amazing Grace Church", denomination: "Reformed Baptist", city: "Catskill", state: "NY", lat: 42.21, lng: -73.86, position: "anti-zionist", phone: "(518) 678-3133", website: true, founded: 1995, attendance: 140, blurb: "A Reformed Baptist church committed to biblical, confessional Christianity. Source: Founders Ministries network.", pastor: "Pastor Henry Coombs" },
  { id: 3, name: "Apologia Church", denomination: "Reformed Baptist", city: "Mesa", state: "AZ", lat: 33.41, lng: -111.83, position: "anti-zionist", phone: "(909) 654-5679", website: true, founded: 2012, attendance: 850, blurb: "Known for apologetics ministry, committed to Reformed theology and cultural engagement.", pastor: "Pastor Jeff Durbin" },
  { id: 4, name: "Apologia Church Utah", denomination: "Reformed Baptist", city: "South Jordan", state: "UT", lat: 40.56, lng: -111.93, position: "anti-zionist", phone: "(801) 555-0142", website: true, founded: 2018, attendance: 320, blurb: "Sister congregation to Apologia Church, committed to Reformed theology and apologetics.", pastor: "Pastor Luke Pierson" },
  { id: 5, name: "Bryce Avenue Presbyterian Church", denomination: "PCA", city: "White Rock", state: "NM", lat: 35.83, lng: -106.20, position: "anti-zionist", phone: "(505) 672-4444", website: true, founded: 1955, attendance: 180, blurb: "A Presbyterian Church in America congregation in northern New Mexico.", pastor: "Rev. Mark Daniels" },
  { id: 6, name: "Calvin Orthodox Presbyterian Church", denomination: "OPC", city: "Phoenix", state: "AZ", lat: 33.45, lng: -112.07, position: "anti-zionist", phone: "(602) 264-3389", website: true, founded: 1964, attendance: 95, blurb: "An Orthodox Presbyterian congregation holding to the Westminster Standards.", pastor: "Rev. Glen Clary" },
  { id: 7, name: "Christ Reformed Church", denomination: "URCNA", city: "Anaheim", state: "CA", lat: 33.84, lng: -117.91, position: "anti-zionist", phone: "(714) 535-2274", website: true, founded: 1978, attendance: 240, blurb: "United Reformed congregation committed to the Three Forms of Unity.", pastor: "Rev. Christopher Gordon" },
  { id: 8, name: "Cornerstone Presbyterian", denomination: "PCA", city: "Franklin", state: "TN", lat: 35.92, lng: -86.86, position: "non-zionist", phone: "(615) 794-3393", website: true, founded: 1989, attendance: 410, blurb: "A growing Presbyterian Church in America congregation in Middle Tennessee.", pastor: "Rev. Stephen Murray" },
  { id: 9, name: "Covenant Reformed Baptist", denomination: "Reformed Baptist", city: "Easley", state: "SC", lat: 34.83, lng: -82.60, position: "anti-zionist", phone: "(864) 855-1133", website: true, founded: 2001, attendance: 165, blurb: "Confessional Baptist church holding the 1689 London Baptist Confession of Faith.", pastor: "Pastor Tom Lyon" },
  { id: 10, name: "Faith Presbyterian Church", denomination: "OPC", city: "Akron", state: "OH", lat: 41.08, lng: -81.52, position: "anti-zionist", phone: "(330) 928-4543", website: false, founded: 1947, attendance: 130, blurb: "Orthodox Presbyterian congregation in northeast Ohio.", pastor: "Rev. Daniel Patterson" },
  { id: 11, name: "First Baptist Church", denomination: "Reformed Baptist", city: "Bryan", state: "TX", lat: 30.67, lng: -96.37, position: "non-zionist", phone: "(979) 822-2345", website: true, founded: 1866, attendance: 380, blurb: "Historic Baptist congregation with Reformed convictions.", pastor: "Pastor Voddie Baucham Jr." },
  { id: 12, name: "Grace Bible Church", denomination: "Bible Church", city: "College Station", state: "TX", lat: 30.63, lng: -96.33, position: "anti-zionist", phone: "(979) 776-1700", website: true, founded: 1973, attendance: 920, blurb: "Independent Bible church serving the Aggie community for over 50 years.", pastor: "Pastor Stephen Underwood" },
  { id: 13, name: "Grace Community Church", denomination: "Independent", city: "Sun Valley", state: "CA", lat: 34.22, lng: -118.36, position: "anti-zionist", phone: "(818) 909-5500", website: true, founded: 1956, attendance: 8500, blurb: "Independent expository preaching church led by John MacArthur for over 50 years.", pastor: "Pastor John MacArthur" },
  { id: 14, name: "Heritage Reformed Congregation", denomination: "HRC", city: "Grand Rapids", state: "MI", lat: 42.96, lng: -85.65, position: "anti-zionist", phone: "(616) 977-0599", website: true, founded: 1995, attendance: 280, blurb: "Heritage Reformed Congregation rooted in Dutch Reformed tradition.", pastor: "Rev. Joel Beeke" },
  { id: 15, name: "Immanuel Baptist Church", denomination: "Reformed Baptist", city: "Sacramento", state: "CA", lat: 38.58, lng: -121.49, position: "anti-zionist", phone: "(916) 422-6700", website: true, founded: 1991, attendance: 320, blurb: "Reformed Baptist church in California's capital region.", pastor: "Pastor Don Lindblad" },
  { id: 16, name: "Indian Hills Community Church", denomination: "Bible Church", city: "Lincoln", state: "NE", lat: 40.81, lng: -96.70, position: "non-zionist", phone: "(402) 483-4541", website: true, founded: 1969, attendance: 1200, blurb: "Independent Bible church known for verse-by-verse expository preaching.", pastor: "Pastor Gil Rugh" },
  { id: 17, name: "Lakeside Christian Fellowship", denomination: "Independent", city: "Knoxville", state: "TN", lat: 35.96, lng: -83.92, position: "anti-zionist", phone: "(865) 690-1414", website: true, founded: 2003, attendance: 220, blurb: "Independent fellowship committed to the authority of Scripture.", pastor: "Pastor Robert Hayes" },
  { id: 18, name: "Mount Olive Baptist", denomination: "Reformed Baptist", city: "Nashville", state: "TN", lat: 36.16, lng: -86.78, position: "non-zionist", phone: "(615) 297-1188", website: true, founded: 1924, attendance: 540, blurb: "Historic Baptist church with strong expository pulpit ministry.", pastor: "Pastor William Pearson" },
  { id: 19, name: "New Covenant Presbyterian", denomination: "PCA", city: "Birmingham", state: "AL", lat: 33.52, lng: -86.81, position: "anti-zionist", phone: "(205) 879-8911", website: true, founded: 1981, attendance: 410, blurb: "Presbyterian Church in America congregation in Birmingham.", pastor: "Rev. Harry Reeder III" },
  { id: 20, name: "Old Path Baptist Church", denomination: "Reformed Baptist", city: "Mount Carmel", state: "TN", lat: 36.55, lng: -82.67, position: "anti-zionist", phone: "(423) 357-6900", website: true, founded: 2007, attendance: 110, blurb: "Confessional Baptist church holding to historic Reformed Baptist distinctives.", pastor: "Pastor Mike Renihan" },
  { id: 21, name: "Pilgrim Presbyterian Church", denomination: "OPC", city: "Bangor", state: "ME", lat: 44.80, lng: -68.78, position: "anti-zionist", phone: "(207) 942-1655", website: false, founded: 1973, attendance: 75, blurb: "Small but faithful OPC congregation in northern New England.", pastor: "Rev. Adam Naranjo" },
  { id: 22, name: "Providence Baptist Church", denomination: "Reformed Baptist", city: "Raleigh", state: "NC", lat: 35.78, lng: -78.64, position: "anti-zionist", phone: "(919) 847-9550", website: true, founded: 1978, attendance: 1850, blurb: "Reformed Baptist church with a global missions emphasis.", pastor: "Pastor Don Whitney" },
  { id: 23, name: "Redeemer Presbyterian", denomination: "PCA", city: "Austin", state: "TX", lat: 30.27, lng: -97.74, position: "non-zionist", phone: "(512) 459-7445", website: true, founded: 1992, attendance: 680, blurb: "PCA congregation serving central Austin with a focus on city ministry.", pastor: "Rev. David Owens" },
  { id: 24, name: "Sovereign Grace Fellowship", denomination: "Reformed Baptist", city: "Boise", state: "ID", lat: 43.62, lng: -116.21, position: "anti-zionist", phone: "(208) 322-4499", website: true, founded: 1999, attendance: 240, blurb: "Reformed Baptist church serving the Treasure Valley.", pastor: "Pastor Jim Domm" },
  { id: 25, name: "Trinity Reformed Church", denomination: "URCNA", city: "Moscow", state: "ID", lat: 46.73, lng: -116.99, position: "anti-zionist", phone: "(208) 882-0408", website: true, founded: 2001, attendance: 320, blurb: "United Reformed congregation in the Palouse region.", pastor: "Rev. Toby Sumpter" },
  { id: 26, name: "Westminster Reformed Church", denomination: "OPC", city: "Plymouth", state: "MI", lat: 42.37, lng: -83.47, position: "anti-zionist", phone: "(734) 459-9550", website: true, founded: 1969, attendance: 180, blurb: "Orthodox Presbyterian congregation in suburban Detroit.", pastor: "Rev. Charles Biggs" },
  { id: 27, name: "Zion Reformed Baptist", denomination: "Reformed Baptist", city: "Charlotte", state: "NC", lat: 35.23, lng: -80.84, position: "anti-zionist", phone: "(704) 535-1010", website: true, founded: 2004, attendance: 290, blurb: "Reformed Baptist church holding to the 1689 confession.", pastor: "Pastor Conrad Mbewe" },
  { id: 28, name: "Bethel Bible Church", denomination: "Bible Church", city: "Tyler", state: "TX", lat: 32.35, lng: -95.30, position: "non-zionist", phone: "(903) 561-3690", website: true, founded: 1976, attendance: 420, blurb: "Independent Bible church with a strong commitment to expository preaching.", pastor: "Pastor Jim Hall" },
  { id: 29, name: "Christ Covenant Church", denomination: "PCA", city: "Matthews", state: "NC", lat: 35.12, lng: -80.72, position: "anti-zionist", phone: "(704) 814-1100", website: true, founded: 1985, attendance: 2400, blurb: "Large Presbyterian Church in America congregation outside Charlotte.", pastor: "Rev. Kevin DeYoung" },
  { id: 30, name: "Reformation Heritage Church", denomination: "URCNA", city: "Belleville", state: "IL", lat: 38.52, lng: -89.98, position: "anti-zionist", phone: "(618) 416-7100", website: true, founded: 2010, attendance: 95, blurb: "United Reformed church plant in southern Illinois.", pastor: "Rev. Brian Vos" }
];

window.STATE_COUNTS = {
  AL: 78, AK: 12, AZ: 145, AR: 56, CA: 412, CO: 124, CT: 38, DE: 14,
  FL: 287, GA: 198, HI: 18, ID: 89, IL: 167, IN: 142, IA: 78, KS: 92,
  KY: 124, LA: 88, ME: 24, MD: 76, MA: 52, MI: 198, MN: 112, MS: 67,
  MO: 156, MT: 34, NE: 67, NV: 42, NH: 18, NJ: 88, NM: 56, NY: 234,
  NC: 312, ND: 22, OH: 245, OK: 134, OR: 98, PA: 198, RI: 12, SC: 178,
  SD: 28, TN: 245, TX: 478, UT: 56, VT: 14, VA: 178, WA: 145, WV: 56,
  WI: 124, WY: 22
};
